spring.application.name=Trackfolio
spring.config.import=file:env.properties
server.port=${PORT}
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
# JWT
jwt.secret=${JWT_SECRET}
## MAILGUN
mailgun.domainName=${MAILGUN_DOMAIN_NAME}
mailgun.apiKey=${MAILGUN_API_KEY}
## CLOUDINARY
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_API_SECRET}
## TMDB
tmdb.token=${TMDB_TOKEN}
tmdb.base-url=${TMDB_URL}
tmdb.api.key=${TMDB_KEY}